import pytest
import os, sys
import pandas as pd
from madap.data_acquisition import data_acquisition


def test_data_acquisition():
    """Test for checking if data is imported correctly.
    """

    list_of_files = []
    for filename in os.scandir(r"test\testfile\supported"):
        if filename.is_file() and not filename.name.endswith(".xlsx"):
            list_of_files.append(filename)
    ground_truth = {
        "freq": [20000.0, 17698.0, 15661.0, 13859.0, 12264.0, 10852.0, 9603.1, 8497.8, 7519.8, 6654.3, 5888.4,
        5210.7, 4611.0, 4080.3, 3610.6, 3195.1, 2827.3, 2501.9, 2214.0, 1959.2, 1733.7, 1534.1, 1357.6, 1201.3,
        1063.0, 940.69, 832.42, 736.62, 651.84, 576.81, 510.43, 451.68, 399.69, 353.69, 312.98, 276.96, 245.08,
        216.87, 191.91, 169.83, 150.28, 132.98, 117.68, 104.13, 92.148, 81.542],
        "real": [996.4391578692059, 1003.24563475233, 1011.2027542585301, 1019.04849559862, 1027.97123131884,
        1037.1348420234199, 1047.84232505298, 1058.99578993269, 1072.03081563616, 1086.1950413677698,
        1102.28718062171, 1120.11050208946, 1141.57115227531, 1164.9016071876802, 1191.58874082894,
        1222.62783504109, 1256.94455918086, 1296.18958155578, 1340.80398153627, 1390.4599229970802,
        1446.75820448996, 1508.81171744154, 1577.8866255534601, 1655.0793518192002, 1739.6419591204,
        1832.70829311633, 1933.2014357124801, 2044.9918826245603, 2163.9574665903197, 2294.30507978865,
        2432.89785942824, 2583.9709030629, 2748.4606988215196, 2925.7131134756396, 3116.04920078104,
        3324.9211992478304, 3551.0612863913, 3796.1900409630202, 4066.29194253677, 4363.27669386883,
        4681.44823935525, 5035.53867864849, 5418.827826515871, 5842.58505681649, 6306.12605087125, 6814.4806104446],
        "imag" : [318.684884313117, 352.60845784699404, 390.85183832549797, 433.39156681362704, 481.257044137324,
        534.613810886657, 594.874805767423, 662.0094841686599, 737.547713771414, 821.923206135482, 916.32197351455,
        1021.47506382262, 1140.00683375901, 1271.1391021450302, 1417.5608306334, 1581.2129221247599, 1760.89545967637,
        1962.3758516932, 2186.6016570443203, 2434.70584280841, 2710.98033045433, 3016.3683476652195, 3354.7676991807502,
        3731.7308452976704, 4150.1079654898995, 4614.1862496458, 5127.28498448514, 5703.79891403093, 6340.09309684833,
        7052.16877796505, 7840.15804117433, 8721.765568412271, 9710.819111387551, 10817.4215641079, 12044.4067848833,
        13425.715841678999, 14968.1010019215, 16691.830865005, 18617.799939908702, 20796.011333271203, 23206.7102194227,
        25937.013119205098, 28967.5446901241, 32388.1845169748, 36212.918915801696, 40466.4040725478]
    }

    df = pd.DataFrame(data=ground_truth)

    for file in list_of_files:
        pd.testing.assert_frame_equal(data_acquisition.acquire_data(file), df)

def test_data_acquisition_excel():
    list_of_files = []
    for filename in os.scandir(r"test\testfile\supported"):
        if filename.is_file() and filename.name.endswith(".xlsx"):
            list_of_files.append(filename)
        ground_truth = {
        "freq": [20000.00,17698.00,15661.00,13859.00,12264.00,10852.00,9603.10,8497.80,7519.80,6654.30,5888.40,5210.70,4611.00,
        4080.30,3610.60,3195.10,2827.30,2501.90,2214.00,1959.20,1733.70,1534.10,1357.60,1201.30,1063.00,940.69,832.42,736.62,651.84,
        576.81,510.43,451.68,399.69,353.69,312.98,276.96,245.08,216.87,191.91,169.83,150.28,132.98,117.68,104.13,92.148,81.542],
        "real": [996.4391579,1003.245635,1011.202754,1019.048496,1027.971231,1037.134842,1047.842325,1058.99579,1072.030816,
        1086.195041,1102.287181,1120.110502,1141.571152,1164.901607,1191.588741,1222.627835,1256.944559,1296.189582,1340.803982,
        1390.459923,1446.758204,1508.811717,1577.886626,1655.079352,1739.641959,1832.708293,1933.201436,2044.991883,2163.957467,
        2294.30508,2432.897859,2583.970903,2748.460699,2925.713113,3116.049201,3324.921199,3551.061286,3796.190041,4066.291943,
        4363.276694,4681.448239,5035.538679,5418.827827,5842.585057,6306.126051,6814.48061],
        "imag" : [318.6848843,352.6084578,390.8518383,433.3915668,481.2570441,534.6138109,594.8748058,662.0094842,737.5477138,
        821.9232061,916.3219735,1021.475064,1140.006834,1271.139102,1417.560831,1581.212922,1760.89546,1962.375852,2186.601657,
        2434.705843,2710.98033,3016.368348,3354.767699,3731.730845,4150.107965,4614.18625,5127.284984,5703.798914,6340.093097,
        7052.168778,7840.158041,8721.765568,9710.819111,10817.42156,12044.40678,13425.71584,14968.101,16691.83087,18617.79994,
        20796.01133,23206.71022,25937.01312,28967.54469,32388.18452,36212.91892,40466.40407]
    }

    df = pd.DataFrame(data=ground_truth)

    for file in list_of_files:
        pd.testing.assert_frame_equal(data_acquisition.acquire_data(file), df)

def test_data_acquisition_not_supported():
    """Test for checking if wrong datatypes are caught
    """
    list_of_files = []
    for filename in os.scandir(r"test\testfile\not_supported"):
        if filename.is_file():
            list_of_files.append(filename)
    for file in list_of_files:
        with pytest.raises(ValueError):
            data_acquisition.acquire_data(file)
